"""Added Columns estado and municipio in Notificacoes

Revision ID: 89aa49dc9554
Revises: f9d16f797c11
Create Date: 2026-08-24 16:36:13.952425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89aa49dc9554'
down_revision: Union[str, Sequence[str], None] = 'f9d16f797c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notificaçoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('municipio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notificaçoes', schema=None) as batch_op:
        batch_op.drop_column('municipio')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
