"""Adicionada coluna media_urls em Notificacoes

Revision ID: 97f7f7eb6f05
Revises: c8036cf18481
Create Date: 2026-08-01 12:16:37.315504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f7f7eb6f05'
down_revision: Union[str, Sequence[str], None] = 'c8036cf18481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('Notificaçoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_urls', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notificaçoes', schema=None) as batch_op:
        batch_op.drop_column('media_urls')

    # ### end Alembic commands ###
