"""Alter table Superintendencias_Ceara adding column coads

Revision ID: 9a7d6a53a93a
Revises: 7a5a037ebd1f
Create Date: 2026-10-06 09:51:07.005799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7d6a53a93a'
down_revision: Union[str, Sequence[str], None] = '7a5a037ebd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Superintendencias_Ceara', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coads', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Superintendencias_Ceara', schema=None) as batch_op:
        batch_op.drop_column('coads')

    # ### end Alembic commands ###
