"""Created tables Municipios and COADS

Revision ID: a63afbbef081
Revises: da08690d4740
Create Date: 2026-10-07 10:22:40.716323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a63afbbef081'
down_revision: Union[str, Sequence[str], None] = 'da08690d4740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('COADS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coads', sa.String(), nullable=False),
    sa.Column('fk_superintendencia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_superintendencia'], ['Superintendencias_Ceara.id'], name=op.f('fk_COADS_fk_superintendencia_Superintendencias_Ceara')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_COADS'))
    )
    op.create_table('Municipios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('fk_coads', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_coads'], ['COADS.id'], name=op.f('fk_Municipios_fk_coads_COADS')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Municipios'))
    )
    with op.batch_alter_table('Superintendencias_Ceara', schema=None) as batch_op:
        batch_op.drop_column('coads')
        batch_op.drop_column('municipio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Superintendencias_Ceara', schema=None) as batch_op:
        batch_op.add_column(sa.Column('municipio', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('coads', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))

    op.drop_table('Municipios')
    op.drop_table('COADS')
    # ### end Alembic commands ###
