"""Criada a tabela NotificacaoMedia para armazenar as medias das notificações

Revision ID: bfe00546564e
Revises: 97f7f7eb6f05
Create Date: 2026-08-03 10:00:00.675372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe00546564e'
down_revision: Union[str, Sequence[str], None] = '97f7f7eb6f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notificacoes_Media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('notificacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notificacao_id'], ['Notificaçoes.id'], name=op.f('fk_Notificacoes_Media_notificacao_id_Notificaçoes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Notificacoes_Media'))
    )

    with op.batch_alter_table('Notificaçoes', schema=None) as batch_op:
        batch_op.drop_column('media_urls')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notificaçoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_urls', sa.VARCHAR(), nullable=True))

    op.drop_table('Notificacoes_Media')
    # ### end Alembic commands ###
