"""Criacao_tabela_Dados_UBS_e_retirada_do_campo_meio_identificacao

Revision ID: c8036cf18481
Revises: a2f70de4944c
Create Date: 2026-07-02 09:57:09.057352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8036cf18481'
down_revision: Union[str, Sequence[str], None] = 'a2f70de4944c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dados_UBS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Agentes', schema=None) as batch_op:
        batch_op.drop_column("ubs_atuante")
        batch_op.add_column(sa.Column('ubs_atuante', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_ubs_atuante", 'Dados_UBS', ['ubs_atuante'], ['id'])

    with op.batch_alter_table('Notificaçoes', schema=None) as batch_op:
        batch_op.drop_column('meio_identificacao')

    with op.batch_alter_table('UBS', schema=None) as batch_op:
        batch_op.alter_column('ubs',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key("fk_ubs_id", 'Dados_UBS', ['ubs'], ['id'])
        batch_op.create_foreign_key("fk_ubs_municipio", 'Dados_UBS', ['municipio'], ['municipio'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UBS', schema=None) as batch_op:
        batch_op.drop_constraint("fk_ubs_id", type_='foreignkey')
        batch_op.drop_constraint("fk_ubs_municipio", type_='foreignkey')
        batch_op.alter_column('ubs',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('Notificaçoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meio_identificacao', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('Agentes', schema=None) as batch_op:
        batch_op.drop_constraint("fk_ubs_atuante", type_='foreignkey')
        batch_op.create_foreign_key("fk_ubs_atuante", 'UBS', ['ubs_atuante'], ['id'])

    op.drop_table('Dados_UBS')
    # ### end Alembic commands ###
