"""Removed fields email and validado. Added fields cpf, microarea(acs/ace) and verificada

Revision ID: c8a1a74c27a1
Revises: e57b84b84ca1
Create Date: 2026-08-24 15:08:38.966499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a1a74c27a1'
down_revision: Union[str, Sequence[str], None] = 'e57b84b84ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Agentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('microarea', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cpf', sa.String(), nullable=True))
        batch_op.drop_column('email')

    with op.batch_alter_table('Coordenadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(), nullable=True))
        batch_op.drop_column('email')

    with op.batch_alter_table('UBS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(), nullable=True))
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UBS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('cpf')

    with op.batch_alter_table('Coordenadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('cpf')

    with op.batch_alter_table('Agentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('cpf')
        batch_op.drop_column('microarea')

    # ### end Alembic commands ###
