"""Alter the type of the field municipio in the table Superintendencias_Ceara

Revision ID: da9d28a2a0f3
Revises: f75494cf3203
Create Date: 2026-09-09 21:53:09.235439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9d28a2a0f3'
down_revision: Union[str, Sequence[str], None] = 'f75494cf3203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Superintendencias_Ceara', schema=None) as batch_op:
        batch_op.alter_column('municipio',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Superintendencias_Ceara', schema=None) as batch_op:
        batch_op.alter_column('municipio',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
