"""Added the table Coordenadores

Revision ID: e57b84b84ca1
Revises: 6af87f27a482
Create Date: 2026-08-17 22:47:48.518930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57b84b84ca1'
down_revision: Union[str, Sequence[str], None] = '6af87f27a482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Coordenadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Coordenadores'))
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('Coordenadores')
    # ### end Alembic commands ###
