"""Added table Vigilantes_Estadual

Revision ID: f320796cdcc4
Revises: da9d28a2a0f3
Create Date: 2026-09-15 20:46:18.680140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f320796cdcc4'
down_revision: Union[str, Sequence[str], None] = 'da9d28a2a0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Vigilantes_Estadual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Vigilantes_Estadual'))
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('Vigilantes_Estadual')
    # ### end Alembic commands ###
