"""Criada as tabelas Agentes, UBS e Notificações

Revision ID: f4a7ba21a476
Revises: 
Create Date: 2026-06-01 16:43:09.612451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a7ba21a476'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UBS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('ubs', sa.String(), nullable=True),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Agentes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('usb_atuante', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usb_atuante'], ['UBS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Notificaçoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('tipo_evento', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('pessoas_animais_infectados_afetados', sa.Integer(), nullable=True),
    sa.Column('local_ocorrencia', sa.String(), nullable=True),
    sa.Column('meio_identificacao', sa.String(), nullable=True),
    sa.Column('continuidade_situacao', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('acs_ace_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rascunho', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['acs_ace_id'], ['Agentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Notificaçoes')
    op.drop_table('Agentes')
    op.drop_table('UBS')
    # ### end Alembic commands ###
