"""Added tables Superintendencias_Ceara and Vigilancia_Regional

Revision ID: f75494cf3203
Revises: 89aa49dc9554
Create Date: 2026-09-09 14:45:22.272314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75494cf3203'
down_revision: Union[str, Sequence[str], None] = '89aa49dc9554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Superintendencias_Ceara',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Superintendencias_Ceara'))
    )
    op.create_table('Vigilantes_Regional',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('superintendencia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['superintendencia'], ['Superintendencias_Ceara.id'], name=op.f('fk_Vigilantes_Regional_superintendencia_Superintendencias_Ceara')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Vigilantes_Regional'))
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('Vigilantes_Regional')
    op.drop_table('Superintendencias_Ceara')
    # ### end Alembic commands ###
