"""Switched validado to verificada

Revision ID: f9d16f797c11
Revises: c8a1a74c27a1
Create Date: 2026-08-24 15:12:22.469227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d16f797c11'
down_revision: Union[str, Sequence[str], None] = 'c8a1a74c27a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('Notificaçoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verificada', sa.Boolean(), nullable=True))
        batch_op.drop_column('validado')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notificaçoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validado', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('verificada')

    # ### end Alembic commands ###
